### ISSUE TITLE
Next step about HALS_RemotePlugInRegistrar::Get3rdPartyPlugInLoadMethod 

### ISSUE THREAD

**Issue by Niap** [tbodt/System-Audio#1]
When I create a breakpoint on macOS Montery, and get unassembles,as shown below.
<img width="1036" alt="Screen Shot 2022-03-22 at 10 38 26 AM" src="https://user-images.githubusercontent.com/1111528/159397047-8704e989-7fef-49e7-b66f-ac20e3080296.png">
It tells that those two companies are approved by apple? 
First,I reinstall Montery many time in different way. The result are the same.
Then,I use dyld cache tools to export CoreAudio from another computer which never installed audio hijack or auidosiphne. and Hopper app gives the same result.
And Then I Confused.

**Comment by tbodt** [comment]
Correct. macOS has these two apps hardcoded into it as the only apps allowed to inject code into coreaudiod. The LLDB script at https://github.com/tbodt/System-Audio/blob/main/patch-coreaudiod-arm64.lldb hacks around this.

I asked apple to add this app as well, but they ultimately refused. Not much to be done.

**Comment by Niap** [comment]
> Correct. macOS has these two apps hardcoded into it as the only apps allowed to inject code into coreaudiod. The LLDB script at https://github.com/tbodt/System-Audio/blob/main/patch-coreaudiod-arm64.lldb hacks around this.
> 
> I asked apple to add this app as well, but they ultimately refused. Not much to be done.


Thank you .
